# Generated by Django 5.2.5 on 2025-09-04 08:01

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1068_alter_document_created"),
    ]

    operations = [
        VectorExtension(),
    ]
