# Generated by Django 5.2.5 on 2025-09-04 08:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1069_add_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=512,
                help_text="The embedding vector for the document.",
                null=True,
            ),
        ),
    ]
