# Generated by Django 5.2.5 on 2025-09-07 18:01

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1070_document_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1024,
                help_text="The embedding vector for the document. Default is with https://huggingface.co/Qwen/Qwen3-Embedding-0.6B model",
                null=True,
            ),
        ),
    ]
